[[custom_commands]]
phrase = "save to local"
command = 'git add -A && git diff --cached --stat && git commit -m "chore'
timestamp = "1765238547"
source = "user_custom_generated"

[[custom_commands]]
phrase = "can I add a new command"
command = "add and commit with a message you create"
timestamp = "1765313217"
source = "user_custom_edited"
